/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuildingMaterialsRouteImport } from './routes/building-materials'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilitiesManagementRouteImport } from './routes/facilities-management'
import { Route as FitOutRouteImport } from './routes/fit-out'
import { Route as FmConsultancyRouteImport } from './routes/fm-consultancy'
import { Route as HardServicesRouteImport } from './routes/hard-services'
import { Route as HvacRouteImport } from './routes/hvac'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as MepRouteImport } from './routes/mep'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SoftServicesRouteImport } from './routes/soft-services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as WhyPakbuiltRouteImport } from './routes/why-pakbuilt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingMaterialsRoute = BuildingMaterialsRouteImport.update({
  id: '/building-materials',
  path: '/building-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesManagementRoute = FacilitiesManagementRouteImport.update({
  id: '/facilities-management',
  path: '/facilities-management',
  getParentRoute: () => rootRouteImport,
} as any)
const FitOutRoute = FitOutRouteImport.update({
  id: '/fit-out',
  path: '/fit-out',
  getParentRoute: () => rootRouteImport,
} as any)
const FmConsultancyRoute = FmConsultancyRouteImport.update({
  id: '/fm-consultancy',
  path: '/fm-consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const HardServicesRoute = HardServicesRouteImport.update({
  id: '/hard-services',
  path: '/hard-services',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacRoute = HvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const MepRoute = MepRouteImport.update({
  id: '/mep',
  path: '/mep',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftServicesRoute = SoftServicesRouteImport.update({
  id: '/soft-services',
  path: '/soft-services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyPakbuiltRoute = WhyPakbuiltRouteImport.update({
  id: '/why-pakbuilt',
  path: '/why-pakbuilt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building-materials': typeof BuildingMaterialsRoute
  '/contact': typeof ContactRoute
  '/facilities-management': typeof FacilitiesManagementRoute
  '/fit-out': typeof FitOutRoute
  '/fm-consultancy': typeof FmConsultancyRoute
  '/hard-services': typeof HardServicesRoute
  '/hvac': typeof HvacRoute
  '/industries': typeof IndustriesRoute
  '/mep': typeof MepRoute
  '/procurement': typeof ProcurementRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-services': typeof SoftServicesRoute
  '/solutions': typeof SolutionsRoute
  '/why-pakbuilt': typeof WhyPakbuiltRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building-materials': typeof BuildingMaterialsRoute
  '/contact': typeof ContactRoute
  '/facilities-management': typeof FacilitiesManagementRoute
  '/fit-out': typeof FitOutRoute
  '/fm-consultancy': typeof FmConsultancyRoute
  '/hard-services': typeof HardServicesRoute
  '/hvac': typeof HvacRoute
  '/industries': typeof IndustriesRoute
  '/mep': typeof MepRoute
  '/procurement': typeof ProcurementRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-services': typeof SoftServicesRoute
  '/solutions': typeof SolutionsRoute
  '/why-pakbuilt': typeof WhyPakbuiltRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building-materials': typeof BuildingMaterialsRoute
  '/contact': typeof ContactRoute
  '/facilities-management': typeof FacilitiesManagementRoute
  '/fit-out': typeof FitOutRoute
  '/fm-consultancy': typeof FmConsultancyRoute
  '/hard-services': typeof HardServicesRoute
  '/hvac': typeof HvacRoute
  '/industries': typeof IndustriesRoute
  '/mep': typeof MepRoute
  '/procurement': typeof ProcurementRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-services': typeof SoftServicesRoute
  '/solutions': typeof SolutionsRoute
  '/why-pakbuilt': typeof WhyPakbuiltRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/building-materials'
    | '/contact'
    | '/facilities-management'
    | '/fit-out'
    | '/fm-consultancy'
    | '/hard-services'
    | '/hvac'
    | '/industries'
    | '/mep'
    | '/procurement'
    | '/products'
    | '/projects'
    | '/sitemap.xml'
    | '/soft-services'
    | '/solutions'
    | '/why-pakbuilt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/building-materials'
    | '/contact'
    | '/facilities-management'
    | '/fit-out'
    | '/fm-consultancy'
    | '/hard-services'
    | '/hvac'
    | '/industries'
    | '/mep'
    | '/procurement'
    | '/products'
    | '/projects'
    | '/sitemap.xml'
    | '/soft-services'
    | '/solutions'
    | '/why-pakbuilt'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/building-materials'
    | '/contact'
    | '/facilities-management'
    | '/fit-out'
    | '/fm-consultancy'
    | '/hard-services'
    | '/hvac'
    | '/industries'
    | '/mep'
    | '/procurement'
    | '/products'
    | '/projects'
    | '/sitemap.xml'
    | '/soft-services'
    | '/solutions'
    | '/why-pakbuilt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildingMaterialsRoute: typeof BuildingMaterialsRoute
  ContactRoute: typeof ContactRoute
  FacilitiesManagementRoute: typeof FacilitiesManagementRoute
  FitOutRoute: typeof FitOutRoute
  FmConsultancyRoute: typeof FmConsultancyRoute
  HardServicesRoute: typeof HardServicesRoute
  HvacRoute: typeof HvacRoute
  IndustriesRoute: typeof IndustriesRoute
  MepRoute: typeof MepRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoftServicesRoute: typeof SoftServicesRoute
  SolutionsRoute: typeof SolutionsRoute
  WhyPakbuiltRoute: typeof WhyPakbuiltRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building-materials': {
      id: '/building-materials'
      path: '/building-materials'
      fullPath: '/building-materials'
      preLoaderRoute: typeof BuildingMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities-management': {
      id: '/facilities-management'
      path: '/facilities-management'
      fullPath: '/facilities-management'
      preLoaderRoute: typeof FacilitiesManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fit-out': {
      id: '/fit-out'
      path: '/fit-out'
      fullPath: '/fit-out'
      preLoaderRoute: typeof FitOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fm-consultancy': {
      id: '/fm-consultancy'
      path: '/fm-consultancy'
      fullPath: '/fm-consultancy'
      preLoaderRoute: typeof FmConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hard-services': {
      id: '/hard-services'
      path: '/hard-services'
      fullPath: '/hard-services'
      preLoaderRoute: typeof HardServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac': {
      id: '/hvac'
      path: '/hvac'
      fullPath: '/hvac'
      preLoaderRoute: typeof HvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mep': {
      id: '/mep'
      path: '/mep'
      fullPath: '/mep'
      preLoaderRoute: typeof MepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soft-services': {
      id: '/soft-services'
      path: '/soft-services'
      fullPath: '/soft-services'
      preLoaderRoute: typeof SoftServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-pakbuilt': {
      id: '/why-pakbuilt'
      path: '/why-pakbuilt'
      fullPath: '/why-pakbuilt'
      preLoaderRoute: typeof WhyPakbuiltRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildingMaterialsRoute: BuildingMaterialsRoute,
  ContactRoute: ContactRoute,
  FacilitiesManagementRoute: FacilitiesManagementRoute,
  FitOutRoute: FitOutRoute,
  FmConsultancyRoute: FmConsultancyRoute,
  HardServicesRoute: HardServicesRoute,
  HvacRoute: HvacRoute,
  IndustriesRoute: IndustriesRoute,
  MepRoute: MepRoute,
  ProcurementRoute: ProcurementRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoftServicesRoute: SoftServicesRoute,
  SolutionsRoute: SolutionsRoute,
  WhyPakbuiltRoute: WhyPakbuiltRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
